name: Build WebFilter Plugin (x86_64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENWRT_VERSION: 23.05.2
  TARGET: x86/64

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-venv python3-dev \
            rsync unzip zlib1g-dev file wget libtool-bin automake autoconf libpam0g-dev \
            liblzma-dev libsnmp-dev tree

      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git --branch v${{ env.OPENWRT_VERSION }} --depth 1
          cd openwrt
          echo "OpenWrt版本验证: $(cat include/version.mk | grep VERSION_NUMBER)"

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a -p luci
          ./scripts/feeds install luci-compat libpam liblzma libnetsnmp

      - name: Add WebFilter plugin
        run: |
          cd openwrt
          # 使用标准包目录结构
          mkdir -p package/network/services
          rm -rf package/network/services/luci-app-webfilter
          
          # 克隆到标准目录
          git clone --depth=1 https://github.com/lj8812/luci-app-webfilter.git \
            package/network/services/luci-app-webfilter
          
          # 生成包索引
          ./scripts/feeds install -a
          
          # 目录结构验证
          echo "=== 插件目录结构 ==="
          tree -L 3 package/network/services/luci-app-webfilter
          
          # 关键文件检查
          [ -f "package/network/services/luci-app-webfilter/Makefile" ] || { 
            echo "::error::Makefile缺失！当前路径: $(pwd)";
            find package/ -name '*webfilter*' -exec echo "发现文件: {}" \; ;
            exit 1;
          }

          # 23.05版本适配补丁
          sed -i 's/iptables /iptables-legacy /g' package/network/services/luci-app-webfilter/root/etc/init.d/webfilter
          sed -i 's/iptables-save /iptables-legacy-save /g' package/network/services/luci-app-webfilter/root/etc/init.d/webfilter

      - name: Configure target
        run: |
          cd openwrt
          cat >> .config << 'EOF'
          # 硬件架构
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y

          # 必要内核模块
          CONFIG_PACKAGE_kmod-nfnetlink=y
          CONFIG_PACKAGE_kmod-ipt-ipset=y
          CONFIG_PACKAGE_kmod-nf-conntrack=y

          # 主插件
          CONFIG_PACKAGE_luci-app-webfilter=y
          CONFIG_PACKAGE_luci-i18n-webfilter-zh-cn=y

          # Luci依赖
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-lib-ipkg=y

          # 显式依赖
          CONFIG_PACKAGE_iptables-legacy=y
          CONFIG_PACKAGE_iptables-legacy-utils=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_dnsmasq-full=y

          # 隐式依赖
          CONFIG_PACKAGE_libipset=y
          CONFIG_PACKAGE_libmnl=y
          CONFIG_PACKAGE_libubus=y
          CONFIG_PACKAGE_libblobmsg-json=y
          CONFIG_PACKAGE_libjson-c=y
          CONFIG_PACKAGE_libuci=y
          CONFIG_PACKAGE_libopenssl=y

          # 语言支持
          CONFIG_LUCI_LANG_zh-cn=y

          # 禁用冲突包
          CONFIG_PACKAGE_dnsmasq=n
          EOF

          # 应用配置
          make defconfig
          echo "=== 最终有效配置 ==="
          ./scripts/diffconfig.sh

      - name: Build toolchain
        run: |
          cd openwrt
          make toolchain/install -j$(nproc) V=s

      - name: 清理并编译
        run: |
          cd openwrt
          # 强制清理残留
          rm -rf tmp/ package/network/services/luci-app-webfilter/ipkg-*
          
          # 预生成索引
          make package/index V=s
          
          echo "=== 编译前验证 ==="
          ls -l package/network/services/luci-app-webfilter/Makefile
          grep 'luci-app-webfilter' package/feeds/luci.index
          
          # 带调试的清理步骤
          echo "::group::执行清理"
          make package/network/services/luci-app-webfilter/clean V=sc || {
            echo "::warning::清理失败，尝试继续编译";
            true;
          }
          echo "::endgroup::"
          
          # 详细编译
          echo "::group::编译详细日志"
          {
            make package/network/services/luci-app-webfilter/compile -j1 V=sc 2>&1 | tee build.log
          } || {
            echo "::error::编译失败，错误摘要："
            grep -C10 'ERROR:' build.log
            exit 1
          }
          echo "::endgroup::"
          
          # 产物验证
          if ! ls bin/packages/x86_64/base/luci-app-webfilter*.ipk >/dev/null 2>&1; then
            echo "::error::编译产物未生成，请检查依赖关系"
            grep 'missing dependencies' build.log | sort | uniq
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webfilter-x86_64
          path: |
            openwrt/bin/packages/x86_64/base/luci-app-webfilter*.ipk
            openwrt/build.log
