name: Build WebFilter Plugin (x86_64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENWRT_VERSION: 23.05.2
  TARGET: x86/64

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-venv python3-dev \
            rsync unzip zlib1g-dev file wget libtool-bin automake autoconf libpam0g-dev \
            liblzma-dev libsnmp-dev tree

      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git --branch v${{ env.OPENWRT_VERSION }} --depth 1
          cd openwrt
          echo "OpenWrt版本验证: $(cat include/version.mk | grep VERSION_NUMBER)"

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a -p luci
          ./scripts/feeds install luci-compat libpam liblzma libnetsnmp

      - name: Add WebFilter plugin
        run: |
          cd openwrt
          rm -rf package/luci-app-webfilter
          
          # 克隆并修复仓库结构
          git clone --depth=1 https://github.com/lj8812/luci-app-webfilter.git package/luci-app-webfilter
          
          # 目录结构验证
          echo "=== 插件目录结构 ==="
          tree -L 3 package/luci-app-webfilter
          
          # 关键文件检查
          [ -f "package/luci-app-webfilter/Makefile" ] || { echo "::error::Makefile缺失！"; exit 1; }
          [ -d "package/luci-app-webfilter/root" ] || echo "::warning::root目录缺失，可能影响安装脚本"

          # 23.05版本适配补丁
          sed -i 's/iptables /iptables-legacy /g' package/luci-app-webfilter/root/etc/init.d/webfilter
          sed -i 's/iptables-save /iptables-legacy-save /g' package/luci-app-webfilter/root/etc/init.d/webfilter

      - name: Configure target
        run: |
          cd openwrt
          cat >> .config << 'EOF'
          # 硬件架构
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y

          # 主插件
          CONFIG_PACKAGE_luci-app-webfilter=y

          # Luci依赖
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-lib-ipkg=y
          CONFIG_PACKAGE_luci-i18n-webfilter-zh-cn=y

          # 显式依赖
          CONFIG_PACKAGE_iptables-legacy=y
          CONFIG_PACKAGE_iptables-legacy-utils=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_dnsmasq-full=y
          CONFIG_PACKAGE_kmod-ipt-ipset=y

          # 隐式依赖
          CONFIG_PACKAGE_libipset=y
          CONFIG_PACKAGE_libmnl=y
          CONFIG_PACKAGE_libubus=y
          CONFIG_PACKAGE_libblobmsg-json=y
          CONFIG_PACKAGE_libjson-c=y
          CONFIG_PACKAGE_libuci=y
          CONFIG_PACKAGE_libopenssl=y

          # 禁用冲突包
          CONFIG_PACKAGE_dnsmasq=n
          EOF

          # 应用配置
          make defconfig
          echo "=== 最终有效配置 ==="
          ./scripts/diffconfig.sh

      - name: Build toolchain
        run: |
          cd openwrt
          make toolchain/install -j$(nproc) V=s

      - name: 清理并编译
        run: |
          cd openwrt
          # 确保包存在
          if [ ! -d "package/luci-app-webfilter" ]; then
            echo "::error::luci-app-webfilter包路径不存在"
            exit 1
          fi
          # 详细清理
          make package/luci-app-webfilter/clean V=sc
          echo "::group::编译详细日志"
          make package/luci-app-webfilter/compile -j1 V=sc 2>&1 | tee build.log
          echo "::endgroup::"
          # 错误分析...
          if grep -q "No rule to make target" build.log; then
            echo "::error::包结构验证失败，请检查Makefile路径"
            exit 1
          fi
          if grep -q "missing dependencies" build.log; then
            echo "::warning::发现未声明的依赖项："
            grep "missing dependencies" build.log | awk -F: '{print $2}' | sort | uniq
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webfilter-x86_64
          path: |
            openwrt/bin/packages/x86_64/base/luci-app-webfilter*.ipk
            openwrt/build.log
