name: Build Control WebRestriction Plugin (x86_64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENWRT_VERSION: 23.05.2
  TARGET: x86/64

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    env:
      TERM: dumb  # 强制设置非交互式终端类型
      WORKSPACE: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
            gettext git libncursesw5-dev libssl-dev python3 python3-venv python3-dev \
            rsync unzip zlib1g-dev file wget libtool-bin automake autoconf libpam0g-dev \
            liblzma-dev libsnmp-dev  # 关键：使用 libncursesw5-dev

      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git --branch v${{ env.OPENWRT_VERSION }} --depth 1
          cd openwrt
          mkdir -p host
          touch host/.prereq-build
          chmod -R 755 host

      - name: Prepare prerequisite directories
        run: |
          cd openwrt
          mkdir -p staging_dir/host/bin
          mkdir -p staging_dir/target-x86_64_musl/usr/bin
          chmod -R 755 staging_dir

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a -p luci
          ./scripts/feeds install luci-base luci-compat

      - name: Add plugin
        run: |
          cd openwrt
          git clone https://github.com/lj8812/luci-app-blockclient.git package/luci-app-blockclient

      - name: Configure target (关键修复)
        run: |
          cd openwrt
          # 非交互式配置流程
          stty sane  # 重置终端状态
          yes "" | make defconfig  # 自动应答所有提示
          
          cat >> .config << EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_PACKAGE_luci-base=y
          CONFIG_PACKAGE_csstidy=y
          CONFIG_PACKAGE_luci-app-blockclient=y
          CONFIG_PACKAGE_luci-i18n-blockclient-zh-cn=y
          CONFIG_PACKAGE_iptables=y
          CONFIG_PACKAGE_dnsmasq-full=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_kmod-ipt-core=y
          CONFIG_PACKAGE_kmod-ipt-ipset=y
          EOF
          
          make olddefconfig  # 应用新配置

      - name: Build dependencies
        run: |
          cd openwrt
          # 单线程编译基础组件
          make -j1 tools/install V=s
          make -j1 toolchain/install V=s
          make -j1 package/luci-base/compile V=s

      - name: Build plugin
        run: |
          cd openwrt
          export STAGING_DIR_HOST=${{ env.WORKSPACE }}/openwrt/staging_dir/host
          make package/luci-app-blockclient/compile -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blockclient-x86_64
          path: openwrt/bin/packages/x86_64/base/luci-app-blockclient*.ipk
