name: Build NetGuard Plugin Only

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENWRT_VERSION: 22.03.5      # 推荐与目标路由器的 OpenWrt 版本一致
  TARGET_PLATFORM: x86_64       # 根据实际架构修改（如 ramips/mt7621 等）

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev

      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git --branch v${{ env.OPENWRT_VERSION }} --depth 1
          cd openwrt

      - name: Add plugin to packages
        run: |
          cd openwrt
          git clone https://github.com/xxtt8812/luci-app-netguard.git package/luci-app-netguard

      - name: Update feeds and install deps
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install libnfnetlink libnetfilter-log

      - name: Configure plugin
        run: |
          cd openwrt
          echo "CONFIG_PACKAGE_luci-app-netguard=y" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-netguard-zh-cn=y" >> .config
          make defconfig

      - name: Build plugin package
        run: |
          cd openwrt
          make package/luci-app-netguard/compile -j$(nproc) V=s

      - name: Upload IPK artifact
        uses: actions/upload-artifact@v3
        with:
          name: netguard-ipk
          path: openwrt/bin/packages/*/base/luci-app-netguard*.ipk
