name: Build WebFilter Plugin (x86_64)
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  OPENWRT_VERSION: 23.05.2
  TARGET: x86_64
jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-venv python3-dev \
            rsync unzip zlib1g-dev file wget libtool-bin automake autoconf libpam0g-dev \
            liblzma-dev libsnmp-dev tree

      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git --branch v${{ env.OPENWRT_VERSION }} --depth 1
          cd openwrt
          echo "OpenWrt版本验证: $(grep 'VERSION_NUMBER:=' include/version.mk | cut -d' ' -f2)"

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -p luci luci-compat libpam liblzma libnetsnmp

      - name: Add WebFilter plugin
        run: |
          cd openwrt
          mkdir -p package/network/services
          rm -rf package/network/services/luci-app-webfilter
          git clone --depth=1 https://github.com/lj8812/luci-app-webfilter.git package/network/services/luci-app-webfilter
          ./scripts/feeds install -a
          
          echo "=== 插件目录结构 ==="
          tree -L 3 package/network/services/luci-app-webfilter
          
          if [ ! -f "package/network/services/luci-app-webfilter/Makefile" ]; then
            echo "::error::Makefile缺失！当前路径: $(pwd)"
            find package/ -name '*webfilter*' -exec echo "发现文件: {}" \;
            exit 1
          fi
          
          # 完整修复iptables替换命令
          sed -i 's/iptables /iptables-legacy /g' package/network/services/luci-app-webfilter/Makefile

      - name: Build plugin
        run: |
          cd openwrt
          make defconfig
          make package/network/services/luci-app-webfilter/compile -j$(nproc) V=s
