name: Build Control WebRestriction Plugin (x86_64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENWRT_VERSION: 23.05.2
  TARGET: x86/64

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-venv python3-dev \
            rsync unzip zlib1g-dev file wget libtool-bin automake autoconf libpam0g-dev \
            liblzma-dev libsnmp-dev
      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git --branch v${{ env.OPENWRT_VERSION }} --depth 1
          cd openwrt
      - name: Update feeds with luci-compat
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install luci-compat libpam liblzma libnetsnmp
      - name: Add plugin
        run: |
          cd openwrt
          git clone https://github.com/lj8812/luci-app-control-webrestriction.git package/luci-app-control-webrestriction
      - name: Configure target
        run: |
          cd openwrt
          cat >> .config << EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_PACKAGE_luci-app-control-webrestriction=y
		      CONFIG_PACKAGE_dnsmasq_full_dnssec=y
          CONFIG_PACKAGE_luci-compat=y
          EOF
          make defconfig
      - name: Build toolchain
        run: |
          cd openwrt
          make toolchain/install -j$(nproc) V=s
      - name: Build plugin
        run: |
          cd openwrt
          make package/luci-app-control-webrestriction/compile -j$(nproc) V=s
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: control-webrestriction-x86_64
          path: openwrt/bin/packages/x86_64/base/luci-app-control-webrestriction*.ipk
