name: Build Control WebRestriction Plugin (x86_64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENWRT_VERSION: 23.05.2
  TARGET: x86/64

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-venv python3-dev \
            rsync unzip zlib1g-dev file wget libtool-bin automake autoconf libpam0g-dev \
            liblzma-dev libsnmp-dev

      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git --branch v${{ env.OPENWRT_VERSION }} --depth 1
          cd openwrt

      - name: Update feeds with luci-compat
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install luci-compat libpam liblzma libnetsnmp

      - name: Add plugin
        run: |
          cd openwrt
          git clone https://github.com/lj8812/luci-app-webrestriction.git  package/luci-app-webrestriction
          # ========== 新增修复步骤 ==========
          cd package/luci-app-webrestriction
          sed -i 's/^    /\t/' Makefile  # 修复Makefile缩进
          
          # 验证Tab缩进（显示^I表示成功）
          echo "::group::Makefile缩进检查"
          cat -e -t -v Makefile | grep -m 3 '^\^I'
          [ $? -eq 0 ] && echo "✅ Tab缩进验证通过" || { echo "❌ Tab缩进异常"; exit 1; }
          echo "::endgroup::"
          cd ..
          # ================================

      - name: Configure target
        run: |
          cd openwrt
          # 写入基础配置
          cat >> .config << EOF
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86=y
          EOF

          # 追加插件依赖配置
          cat >> .config << EOF
          # Web访问限制插件依赖
          CONFIG_PACKAGE_luci-app-webrestriction=y
          CONFIG_PACKAGE_luci-i18n-webrestriction-zh-cn=y
          CONFIG_PACKAGE_luci-base=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_rpcd=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_iptables-nft=y
          CONFIG_PACKAGE_kmod-ipt-core=y
          CONFIG_PACKAGE_kmod-nf-conntrack=y
          CONFIG_PACKAGE_libnftnl=y
          CONFIG_PACKAGE_libiptext=y
          CONFIG_PACKAGE_libubus-lua=y
          CONFIG_PACKAGE_libuci-lua=y
          EOF
          
          make defconfig

      - name: Build toolchain
        run: |
          cd openwrt
          make toolchain/install -j$(nproc) V=s

      - name: Build plugin
        run: |
          cd openwrt
          make package/luci-app-webrestriction/compile -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webrestriction-x86_64
          path: openwrt/bin/packages/x86_64/base/luci-app-webrestriction*.ipk
