name: Build Control WebRestriction Plugin (x86_64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENWRT_VERSION: 23.05.2
  TARGET: x86/64

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-venv python3-dev \
            rsync unzip zlib1g-dev file wget libtool-bin automake autoconf libpam0g-dev \
            liblzma-dev libsnmp-dev

      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git --branch v${{ env.OPENWRT_VERSION }} --depth 1
          cd openwrt

      - name: Update feeds (关键修复)
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a -p luci  # 强制安装luci feed
          ./scripts/feeds install luci-base luci-compat  # 显式安装基础组件

      - name: Add plugin
        run: |
          cd openwrt
          git clone https://github.com/lj8812/luci-app-blockclient.git  package/luci-app-blockclient

      - name: Configure target (新增luci-base编译)
        run: |
          cd openwrt
          cat >> .config << EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_PACKAGE_luci-base=y  # 确保基础包启用
          CONFIG_PACKAGE_luci-app-blockclient=y
          CONFIG_PACKAGE_luci-i18n-blockclient-zh-cn=y
          CONFIG_PACKAGE_iptables=y
          CONFIG_PACKAGE_dnsmasq-full=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_kmod-ipt-core=y
          CONFIG_PACKAGE_kmod-ipt-ipset=y
          EOF
          make defconfig

      - name: Build luci-base first (新增步骤)
        run: |
          cd openwrt
          make -j$(nproc) package/luci-base/compile V=s  # 优先编译基础包

      - name: Build toolchain
        run: |
          cd openwrt
          make toolchain/install -j$(nproc) V=s

      - name: Build plugin (修复路径)
        run: |
          cd openwrt
          export STAGING_DIR_HOST=$(pwd)/staging_dir/host  # 设置工具路径变量
          make package/luci-app-blockclient/compile -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blockclient-x86_64
          path: openwrt/bin/packages/x86_64/base/luci-app-blockclient*.ipk
