name: Build Control WebRestriction Plugin (x86_64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENWRT_VERSION: 23.05.2
  TARGET: x86/64
  STAGING_DIR: ${{ github.workspace }}/openwrt/staging_dir  # 全局变量
  STAGING_DIR_HOST: ${{ env.STAGING_DIR }}/host

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get install -y build-essential clang flex g++ gawk libncurses5-dev zlib1g-dev

      - name: Clone OpenWrt source
        run: |
          git clone --depth 1 --branch v${{ env.OPENWRT_VERSION }} https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a -p luci
          ./scripts/feeds install luci-base luci-compat luci-lib-base

      - name: Build host tools
        run: |
          cd openwrt
          make -j1 tools/install V=s
          make -j1 toolchain/install V=s

      - name: Add plugin
        run: |
          cd openwrt
          git clone https://github.com/lj8812/luci-app-blockclient.git package/luci-app-blockclient

      - name: Configure target
        run: |
          cd openwrt
          cat >> .config << EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_PACKAGE_luci-base=y
          CONFIG_PACKAGE_csstidy=y
          CONFIG_PACKAGE_luci-app-blockclient=y
          CONFIG_PACKAGE_luci-i18n-blockclient-zh-cn=y
          CONFIG_PACKAGE_iptables=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_kmod-ipt-core=y
          CONFIG_PACKAGE_kmod-ipt-ipset=y
          EOF
          make defconfig

      - name: Build luci-base
        run: |
          cd openwrt
          export STAGING_DIR_HOST=${{ env.STAGING_DIR_HOST }}
          make -j1 package/luci-base/{clean,compile} V=s

      - name: Build plugin
        run: |
          cd openwrt
          export STAGING_DIR_HOST=${{ env.STAGING_DIR_HOST }}
          make package/luci-app-blockclient/compile -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: openwrt/bin/packages/x86_64/base/luci-app-blockclient_*.ipk
