name: Build Control WebRestriction Plugin (x86_64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENWRT_VERSION: 23.05.2
  TARGET: x86/64

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
      STAGING_DIR: ${{ github.workspace }}/openwrt/staging_dir
      STAGING_DIR_HOST: ${{ github.workspace }}/openwrt/staging_dir/host

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
            gettext git libncursesw5-dev libssl-dev python3 python3-venv python3-dev \
            rsync unzip zlib1g-dev file wget libtool-bin automake autoconf libpam0g-dev \
            liblzma-dev libsnmp-dev

      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git --branch v${{ env.OPENWRT_VERSION }} --depth 1
          cd openwrt
          mkdir -p host
          touch host/.prereq-build
          chmod -R 755 host

      - name: Force install luci-base dependencies
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a -p luci
          ./scripts/feeds install luci-base luci-compat luci-lib-ipkg

      - name: Configure target
        run: |
          cd openwrt
          cat > .config << EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_PACKAGE_luci-base=y
          CONFIG_PACKAGE_luci-lib-ipkg=y
          CONFIG_PACKAGE_csstidy=y
          CONFIG_PACKAGE_luci-app-blockclient=y
          CONFIG_PACKAGE_luci-i18n-blockclient-zh-cn=y
          EOF
          make olddefconfig

      - name: Build luci-base with po2lmo
        run: |
          cd openwrt
          # 强制编译 luci-base 和依赖
          make -j1 tools/compile V=s
          make -j1 toolchain/compile V=s
          make -j1 package/luci-base/{clean,compile} V=s

          # 关键验证步骤
          echo "----- po2lmo 路径验证 -----"
          ls -l $STAGING_DIR_HOST/bin/po2lmo
          file $STAGING_DIR_HOST/bin/po2lmo

      - name: Build plugin
        run: |
          cd openwrt
          export PATH=$STAGING_DIR_HOST/bin:$PATH
          make package/luci-app-blockclient/{clean,compile} -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blockclient-x86_64
          path: openwrt/bin/packages/x86_64/base/luci-app-blockclient*.ipk
