name: Build WebFilter Plugin (x86_64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENWRT_VERSION: 23.05.2
  TARGET: x86/64

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-venv python3-dev \
            rsync unzip zlib1g-dev file wget libtool-bin automake autoconf libpam0g-dev \
            liblzma-dev libsnmp-dev tree

      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git --branch v${{ env.OPENWRT_VERSION }} --depth 1
          cd openwrt
          echo "OpenWrt版本验证: $(grep 'VERSION_NUMBER:=' include/version.mk | cut -d' ' -f2)"

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a -p luci
          ./scripts/feeds install luci-compat libpam liblzma libnetsnmp

      - name: Add WebFilter plugin
        run: |
          cd openwrt
          mkdir -p package/network/services
          rm -rf package/network/services/luci-app-webfilter
          
          git clone --depth=1 https://github.com/lj8812/luci-app-webfilter.git \
            package/network/services/luci-app-webfilter
          
          ./scripts/feeds install -a
          echo "=== 插件目录结构 ==="
          tree -L 3 package/network/services/luci-app-webfilter
          
          if [ ! -f "package/network/services/luci-app-webfilter/Makefile" ]; then
            echo "::error::Makefile缺失！当前路径: $(pwd)"
            find package/ -name '*webfilter*' -exec echo "发现文件: {}" \;
            exit 1
          fi

          sed -i 's/iptables /iptables-legacy /g' package/network/services/luci-app-webfilter/root/etc/init.d/webfilter

      - name: Configure target
        run: |
          cd openwrt
          cat >> .config << 'EOF'
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y

          # 签名工具配置
          CONFIG_SIGNED_PACKAGES=y
          CONFIG_BUILD_TOOLS=y
          CONFIG_PACKAGE_usign=y
          CONFIG_PACKAGE_libubox=y

          # 内核模块
          CONFIG_PACKAGE_kmod-nf-conntrack=y
          CONFIG_PACKAGE_kmod-ipt-core=y
          CONFIG_PACKAGE_kmod-ipt-ipset=y

          # 主插件配置
          CONFIG_PACKAGE_luci-app-webfilter=y
          CONFIG_PACKAGE_luci-i18n-webfilter-zh-cn=y

          # 依赖配置
          CONFIG_PACKAGE_iptables-legacy=y
          CONFIG_PACKAGE_dnsmasq-full=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_luci-compat=y

          # 语言支持
          CONFIG_LUCI_LANG_zh-cn=y

          # 禁用冲突包
          CONFIG_PACKAGE_dnsmasq=n
          EOF

          make defconfig
          echo "=== 最终有效配置 ==="
          ./scripts/diffconfig.sh

      - name: Build toolchain
        run: |
          cd openwrt
          # 分步构建工具链
          make tools/install -j$(nproc) V=s
          make toolchain/install -j$(nproc) V=s
          
          # 显式构建签名工具
          echo "::group::构建签名工具"
          make package/libubox/compile V=sc
          make package/usign/compile V=sc
          echo "::endgroup::"

      - name: 清理并编译
        run: |
          cd openwrt
          rm -rf tmp/ package/network/services/luci-app-webfilter/ipkg-*
          
          echo "::group::生成包索引（忽略签名错误）"
          make package/index V=s IPKG_REMOVE_UNSIGNED=1 || true
          echo "::endgroup::"
          
          echo "::group::执行清理"
          make package/network/services/luci-app-webfilter/clean V=sc || true
          echo "::endgroup::"
          
          echo "::group::编译详细日志"
          {
            make package/network/services/luci-app-webfilter/compile -j1 V=sc 2>&1 | tee build.log
          } || {
            grep -C15 'ERROR:' build.log
            exit 1
          }
          echo "::endgroup::"
          
          if ! ls bin/packages/x86_64/base/luci-app-webfilter*.ipk >/dev/null 2>&1; then
            echo "::error::编译产物验证失败"
            grep -e 'missing' -e 'error' build.log | sort | uniq
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webfilter-x86_64
          path: |
            openwrt/bin/packages/x86_64/base/luci-app-webfilter*.ipk
            openwrt/build.log
