name: Auto Build luci-app-netguard (Docker)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: openwrtorg/sdk:23.05-x86-64  # 根据架构调整

    steps:
    # 核心步骤：拉取远程仓库及子模块
    - name: Checkout remote repository
      uses: actions/checkout@v4
      with:
        repository: xxtt8812/luci-app-netguard  # 指定远程仓库
        submodules: recursive  # 强制递归拉取子模块
        path: package/luci-app-netguard  # 强制符合OpenWrt目录规范

    # OpenWrt环境初始化
    - name: Initialize feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a  # 解决luci.mk依赖

    # 自定义补丁支持（可选）
    - name: Apply patches
      run: |
        if [ -d "patches" ]; then
          git -C package/luci-app-netguard apply $GITHUB_WORKSPACE/patches/*.patch
        fi

    # 多线程编译
    - name: Compile package
      run: |
        cd package/luci-app-netguard
        make -j$(nproc) V=s  # 显示详细日志

    # 产物输出
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: netguard-ipk
        path: bin/packages/*/base/luci-app-netguard*.ipk  # 标准输出路径
